# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macos-10.13'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo This is a bit odd yaml, a text and displayName at the same level...
    xcode-select -v
    xcode-select -p
    pwd
    env
    ls -l ~
    ls -l /Volumes
    ls -l /Applications
    
  displayName: 'Run a multi-line script'
